### ISSUE TITLE
[Bug/Instability] Nodes running on develop keep getting stuck randomly every day or two. 

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#3476]
This issue was initially seen by @UdjinM6 on April 10th, 2020. 

When this occurs the node wasn’t receiving blocks and shutdown wasn’t clear

Originally running 26dec64, on ubuntu 16.04

Node was reporting
```
2020-04-10 00:31:17 socket sending timeout: 1201s
...
2020-04-10 00:31:17 socket sending timeout: 1201s
2020-04-10 00:31:22 socket sending timeout: 1201s
```
That node while running 52bf616 had earlier reported 
```
2020-04-07 00:07:30 socket sending timeout: 1201s
2020-04-07 00:07:30 socket sending timeout: 1201s
2020-04-07 00:07:34 socket sending timeout: 1201s
...
2020-04-07 00:07:34 socket sending timeout: 1201s
```

cb33702 was the prior commit that had been being ran since mid January, so the problem(s) was likely introduced between cb33702 and 52bf616

https://github.com/dashpay/dash/pull/3456 which fixes some deadlocks was created with the intent to fix this issue, however, the issue persists

**Comment by PastaPastaPasta** [comment]
Okay an update, the past 2 to 3 days Udjin xdustinface and I have all been running develop, and ofc we haven't had any crashes / halts. 
We'll keep this issue open for a few more days and see if this current stability remains

**Comment by UdjinM6** [comment]
Good news - I'm not _that_ crazy, bad news - there is a deadlock because of the `ActivateBestChain` in ChainLocks and `SyncWithValidationInterfaceQueue` in `ActivateBestChain` introduced in #3376.

Running e0ff9af2b on mainnet:

```
Thread 26 (Thread 0x7fb0ec7f8700 (LWP 16203)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007fb150d42c26 in __GI___pthread_mutex_lock (
    mutex=0x558fb5b1a280 <CChainState::ActivateBestChain(CValidationState&, CChainParams const&, std::shared_ptr<CBlock const>)::cs_activateBestChain>)
    at ../nptl/pthread_mutex_lock.c:115
#2  0x0000558fb4b27413 in __gthread_mutex_lock () at /usr/include/x86_64-linux-gnu/c++/6/bits/gthr-default.h:748
#3  __gthread_recursive_mutex_lock () at /usr/include/x86_64-linux-gnu/c++/6/bits/gthr-default.h:810
#4  std::recursive_mutex::lock () at /usr/include/c++/6/mutex:105
#5  AnnotatedMixin<std::recursive_mutex>::lock () at ./sync.h:59
#6  std::unique_lock<CCriticalSection>::lock () at /usr/include/c++/6/bits/std_mutex.h:267
#7  CCriticalBlock::Enter () at ./sync.h:128
#8  CCriticalBlock::CCriticalBlock () at ./sync.h:149
#9  0x0000558fb4e3f631 in CChainState::ActivateBestChain () at validation.cpp:2948
#10 0x0000558fb4e45ab9 in ProcessNewBlock () at validation.cpp:3787
#11 0x0000558fb4ca4008 in ProcessMessage () at net_processing.cpp:3187
#12 0x0000558fb4caac24 in PeerLogicValidation::ProcessMessages () at net_processing.cpp:3634
#13 0x0000558fb4c484e8 in CConnman::ThreadMessageHandler () at net.cpp:2718
#14 0x0000558fb4b242b6 in std::function<void ()>::operator()() const () at /usr/include/c++/6/functional:2127
#15 TraceThread<std::function<void ()> >(char const*, std::function<void ()>) () at ./util.h:443
#16 0x0000558fb4bcc88b in std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) () at /usr/include/c++/6/functional:1391
#17 std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)>::operator()() () at /usr/include/c++/6/functional:1380
#18 std::thread::_State_impl<std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)> >::_M_run() ()
    at /usr/include/c++/6/thread:197
#19 0x00007fb15086ce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#20 0x00007fb150d404a4 in start_thread (arg=0x7fb0ec7f8700) at pthread_create.c:456
#21 0x00007fb14ffe1d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 3 (Thread 0x7fb14d459700 (LWP 16144)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fb15086b140 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000558fb4e5d218 in std::__atomic_futex_unsigned<2147483648u>::_M_load_and_test_until () at /usr/include/c++/6/bits/atomic_futex.h:104
#3  std::__atomic_futex_unsigned<2147483648u>::_M_load_and_test () at /usr/include/c++/6/bits/atomic_futex.h:122
#4  std::__atomic_futex_unsigned<2147483648u>::_M_load_when_equal () at /usr/include/c++/6/bits/atomic_futex.h:162
#5  std::__future_base::_State_baseV2::wait () at /usr/include/c++/6/future:328
#6  std::__basic_future<void>::wait () at /usr/include/c++/6/future:662
#7  SyncWithValidationInterfaceQueue () at validationinterface.cpp:165
#8  0x0000558fb4e3f6da in CChainState::ActivateBestChain () at validation.cpp:2960
#9  0x0000558fb4e41b0c in ActivateBestChain () at validation.cpp:3030
#10 0x0000558fb4f46c72 in llmq::CChainLocksHandler::EnforceBestChainLock () at llmq/quorums_chainlocks.cpp:538
#11 0x0000558fb4f4c2ab in operator() () at llmq/quorums_chainlocks.cpp:50
#12 _M_invoke () at /usr/include/c++/6/functional:1731
#13 0x0000558fb4fef8c4 in std::function<void ()>::operator()() const () at /usr/include/c++/6/functional:2127
#14 Repeat () at scheduler.cpp:122
#15 0x0000558fb4ff1f55 in boost::_bi::list3<boost::_bi::value<CScheduler*>, boost::_bi::value<std::function<void ()> >, boost::_bi::value<long> >::operator()<void (*)(CScheduler*, std::function<void ()>, long), boost::_bi::list0>(boost::_bi::type<void>, void (*&)(CScheduler*, std::function<void ()>, long), boost::_bi::list0&, int) ()
    at /root/dash_develop/depends/x86_64-pc-linux-gnu/share/../include/boost/bind/bind.hpp:398
#16 boost::_bi::bind_t<void, void (*)(CScheduler*, std::function<void ()>, long), boost::_bi::list3<boost::_bi::value<CScheduler*>, boost::_bi::value<std::function<void ()> >, boost::_bi::value<long> > >::operator()() () at /root/dash_develop/depends/x86_64-pc-linux-gnu/share/../include/boost/bind/bind.hpp:1294
#17 std::_Function_handler<void (), boost::_bi::bind_t<void, void (*)(CScheduler*, std::function<void ()>, long), boost::_bi::list3<boost::_bi::value<CScheduler*>, boost::_bi::value<std::function<void ()> >, boost::_bi::value<long> > > >::_M_invoke(std::_Any_data const&) () at /usr/include/c++/6/functional:1731
#18 0x0000558fb4ff0e3c in std::function<void ()>::operator()() const () at /usr/include/c++/6/functional:2127
#19 CScheduler::serviceQueue () at scheduler.cpp:83
#20 0x0000558fb4b242b6 in std::function<void ()>::operator()() const () at /usr/include/c++/6/functional:2127
#21 TraceThread<std::function<void ()> >(char const*, std::function<void ()>) () at ./util.h:443
#22 0x0000558fb4b263c7 in boost::_bi::list2<boost::_bi::value<char const*>, boost::_bi::value<std::function<void ()> > >::operator()<void (*)(char const*, std::function<void ()>), boost::_bi::list0>(boost::_bi::type<void>, void (*&)(char const*, std::function<void ()>), boost::_bi::list0&, int) ()
    at /root/dash_develop/depends/x86_64-pc-linux-gnu/share/../include/boost/bind/bind.hpp:319
#23 boost::_bi::bind_t<void, void (*)(char const*, std::function<void ()>), boost::_bi::list2<boost::_bi::value<char const*>, boost::_bi::value<std::function<void ()> > > >::operator()() () at /root/dash_develop/depends/x86_64-pc-linux-gnu/share/../include/boost/bind/bind.hpp:1294
#24 boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(char const*, std::function<void ()>), boost::_bi::list2<boost::_bi::value<char const*>, boost::_bi::value<std::function<void ()> > > > >::run() () at /root/dash_develop/depends/x86_64-pc-linux-gnu/share/../include/boost/thread/detail/thread.hpp:116
#25 0x0000558fb5293eab in thread_proxy ()
#26 0x00007fb150d404a4 in start_thread (arg=0x7fb14d459700) at pthread_create.c:456
#27 0x00007fb14ffe1d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by UdjinM6** [comment]
And now there is also a deadlocked in a reverse direction :/

```
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x000055ec4c5a9056 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) ()
#2  0x000055ec4be2e648 in std::__atomic_futex_unsigned<2147483648u>::_M_load_and_test_until ()
    at /usr/include/c++/5/bits/atomic_futex.h:104
#3  std::__atomic_futex_unsigned<2147483648u>::_M_load_and_test () at /usr/include/c++/5/bits/atomic_futex.h:122
#4  std::__atomic_futex_unsigned<2147483648u>::_M_load_when_equal () at /usr/include/c++/5/bits/atomic_futex.h:162
#5  std::__future_base::_State_baseV2::wait () at /usr/include/c++/5/future:322
#6  std::__basic_future<void>::wait () at /usr/include/c++/5/future:656
#7  SyncWithValidationInterfaceQueue () at validationinterface.cpp:165
#8  0x000055ec4be1117c in CChainState::ActivateBestChain () at validation.cpp:2960
#9  0x000055ec4be1610f in ProcessNewBlock () at validation.cpp:3787
#10 0x000055ec4bc82bae in ProcessMessage () at net_processing.cpp:3187
#11 0x000055ec4bc86f93 in PeerLogicValidation::ProcessMessages () at net_processing.cpp:3634
#12 0x000055ec4bc259e8 in CConnman::ThreadMessageHandler () at net.cpp:2718
#13 0x000055ec4bb05396 in std::function<void ()>::operator()() const () at /usr/include/c++/5/functional:2267
#14 TraceThread<std::function<void ()> >(char const*, std::function<void ()>) () at ./util.h:443
#15 0x000055ec4bbabbab in std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) () at /usr/include/c++/5/functional:1531
#16 std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)>::operator()() ()
    at /usr/include/c++/5/functional:1520
#17 std::thread::_Impl<std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)> >::_M_run() () at /usr/include/c++/5/thread:115
#18 0x000055ec4c581840 in execute_native_thread_routine ()
#19 0x00007ff1f01fc6ba in start_thread (arg=0x7ff19dffb700) at pthread_create.c:333
#20 0x00007ff1efa1341d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7ff1e4d2f700 (LWP 10785)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ff1f01fee42 in __GI___pthread_mutex_lock (
    mutex=0x55ec4cbde260 <CChainState::ActivateBestChain(CValidationState&, CChainParams const&, std::shared_ptr<CBlock const>, bool)::cs_activateBestChain>) at ../nptl/pthread_mutex_lock.c:115
#2  0x000055ec4bb08513 in __gthread_mutex_lock () at /usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:748
#3  __gthread_recursive_mutex_lock () at /usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:810
#4  std::recursive_mutex::lock () at /usr/include/c++/5/mutex:176
#5  AnnotatedMixin<std::recursive_mutex>::lock () at ./sync.h:59
#6  std::unique_lock<CCriticalSection>::lock () at /usr/include/c++/5/mutex:485
#7  CCriticalBlock::Enter () at ./sync.h:128
#8  CCriticalBlock::CCriticalBlock () at ./sync.h:149
#9  0x000055ec4be10d5d in CChainState::ActivateBestChain () at validation.cpp:2948
#10 0x000055ec4be121d3 in ActivateBestChain () at validation.cpp:3030
#11 0x000055ec4bf168fe in llmq::CChainLocksHandler::EnforceBestChainLock () at llmq/quorums_chainlocks.cpp:539
#12 0x000055ec4bf1c0cb in operator() () at llmq/quorums_chainlocks.cpp:50
#13 _M_invoke () at /usr/include/c++/5/functional:1871
#14 0x000055ec4bfbdb64 in std::function<void ()>::operator()() const () at /usr/include/c++/5/functional:2267
#15 Repeat () at scheduler.cpp:122
#16 0x000055ec4bfbfdb5 in boost::_bi::list3<boost::_bi::value<CScheduler*>, boost::_bi::value<std::function<void ()> >, boost::_bi::value<long> >::operator()<void (*)(CScheduler*, std::function<void ()>, long), boost::_bi::list0>(boost::_bi::type<void>, void (*&)(CScheduler*, std::function<void ()>, long), boost::_bi::list0&, int) ()
    at /root/dash_testnet/depends/x86_64-pc-linux-gnu/share/../include/boost/bind/bind.hpp:398
#17 boost::_bi::bind_t<void, void (*)(CScheduler*, std::function<void ()>, long), boost::_bi::list3<boost::_bi::value<CScheduler*>, boost::_bi::value<std::function<void ()> >, boost::_bi::value<long> > >::operator()() ()
    at /root/dash_testnet/depends/x86_64-pc-linux-gnu/share/../include/boost/bind/bind.hpp:1294
#18 std::_Function_handler<void (), boost::_bi::bind_t<void, void (*)(CScheduler*, std::function<void ()>, long), boost::_bi::list3<boost::_bi::value<CScheduler*>, boost::_bi::value<std::function<void ()> >, boost::_bi::value<long> > > >::_M_invoke(std::_Any_data const&) () at /usr/include/c++/5/functional:1871
#19 0x000055ec4bfbeba8 in std::function<void ()>::operator()() const () at /usr/include/c++/5/functional:2267
#20 CScheduler::serviceQueue () at scheduler.cpp:83
#21 0x000055ec4bb05396 in std::function<void ()>::operator()() const () at /usr/include/c++/5/functional:2267
#22 TraceThread<std::function<void ()> >(char const*, std::function<void ()>) () at ./util.h:443
#23 0x000055ec4bb07527 in boost::_bi::list2<boost::_bi::value<char const*>, boost::_bi::value<std::function<void ()> > >::operator()<void (*)(char const*, std::function<void ()>), boost::_bi::list0>(boost::_bi::type<void>, void (*&)(char const*, std::function<void ()>), boost::_bi::list0&, int) () at /root/dash_testnet/depends/x86_64-pc-linux-gnu/share/../include/boost/bind/bind.hpp:319
#24 boost::_bi::bind_t<void, void (*)(char const*, std::function<void ()>), boost::_bi::list2<boost::_bi::value<char const*>, boost::_bi::value<std::function<void ()> > > >::operator()() ()
    at /root/dash_testnet/depends/x86_64-pc-linux-gnu/share/../include/boost/bind/bind.hpp:1294
#25 boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(char const*, std::function<void ()>), boost::_bi::list2<boost::_bi::value<char const*>, boost::_bi::value<std::function<void ()> > > > >::run() ()
    at /root/dash_testnet/depends/x86_64-pc-linux-gnu/share/../include/boost/thread/detail/thread.hpp:116
#26 0x000055ec4c2672c2 in thread_proxy ()
#27 0x00007ff1f01fc6ba in start_thread (arg=0x7ff1e4d2f700) at pthread_create.c:333
#28 0x00007ff1efa1341d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by PastaPastaPasta** [comment]
Seems like this was at least 99% fixed by https://github.com/dashpay/dash/pull/3492

Will reopen if we run into deadlocks again
