### ISSUE TITLE
interface_zmq.py  non-deterministic failure on linux-32 tests

### ISSUE THREAD

**Issue by vijaydasmp** [dashpay/dash#4630]
Steps to reproduce: while python3 test/functional/test_runner.py --randomseed=0 interface_zmq.py; do :; done

 Below is the stacktrace of the failure  
2021-12-20T10:58:17.805000Z TestFramework (INFO): Generate 5 blocks (and 5 coinbase txes)
2021-12-20T10:59:17.901000Z TestFramework (ERROR): Unexpected exception caught during testing
Traceback (most recent call last):
  File "/builds/dashpay/dash/build-ci/dashcore-linux32/test/functional/test_framework/test_framework.py", line 232, in main
    self.run_test()
  File "/builds/dashpay/dash/build-ci/dashcore-linux32/test/functional/interface_zmq.py", line 54, in run_test
    self.test_basic()
  File "/builds/dashpay/dash/build-ci/dashcore-linux32/test/functional/interface_zmq.py", line 89, in test_basic
    txid = hashtx.receive()
  File "/builds/dashpay/dash/build-ci/dashcore-linux32/test/functional/interface_zmq.py", line 33, in receive
    topic, body, seq = self.socket.recv_multipart()
  File "/usr/local/lib/python3.8/dist-packages/zmq/sugar/socket.py", line 625, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 781, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 817, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc
**zmq.error.Again: Resource temporarily unavailable**

Happened on CI for different runs 

https://gitlab.com/dashpay/dash/-/jobs/1902628391

**Comment by vijaydasmp** [comment]
@UdjinM6 @PastaPastaPasta

**Comment by vijaydasmp** [comment]
Now this test is deterministically failing on develop branch pipeline as well.
