### ISSUE TITLE
v0.12.0.38-a47585e dies on disablewallet=1 (segmentation fault)

### ISSUE THREAD

**Issue by schinzelh** [dashpay/dash#486]
Hi,

i tried to run the deamon with disabled wallet ("disablewallet=1). The daemon immediately dies with this log

2015-08-06 19:29:11 Dash version v0.12.0.38-a47585e (2015-08-05 16:37:43 -0700)
2015-08-06 19:29:11 Using OpenSSL version OpenSSL 1.0.1k 8 Jan 2015
2015-08-06 19:29:11 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2015-08-06 19:29:11 Default data directory /mnt/data/test-abe-home/.dash
2015-08-06 19:29:11 Using data directory /mnt/data/test-abe-home/.dash/testnet3
2015-08-06 19:29:11 Using config file /mnt/data/test-abe-home/.dash/dash.conf
2015-08-06 19:29:11 Using at most 125 connections (1024 file descriptors available)
2015-08-06 19:29:11 Using 2 threads for script verification
2015-08-06 19:29:11 Binding RPC on address ::1 port 19998 (IPv4+IPv6 bind any: 0)
2015-08-06 19:29:11 Binding RPC on address 127.0.0.1 port 19998 (IPv4+IPv6 bind any: 0)
2015-08-06 19:29:11 Bound to [::]:19999
2015-08-06 19:29:11 Bound to 0.0.0.0:19999
2015-08-06 19:29:11 init message: Loading block index...
2015-08-06 19:29:11 Opening LevelDB in /mnt/data/test-abe-home/.dash/testnet3/blocks/index
2015-08-06 19:29:11 Opened LevelDB successfully
2015-08-06 19:29:11 Opening LevelDB in /mnt/data/test-abe-home/.dash/testnet3/chainstate
2015-08-06 19:29:11 Opened LevelDB successfully
2015-08-06 19:29:11 LoadBlockIndexDB: last block file = 0
2015-08-06 19:29:11 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=0, size=0, heights=0...0, time=1970-01-01...1970-01-01)
2015-08-06 19:29:11 Checking all blk files are present...
2015-08-06 19:29:11 LoadBlockIndexDB(): transaction index enabled
2015-08-06 19:29:11 Initializing databases...
2015-08-06 19:29:11 Pre-allocating up to position 0x1000000 in blk00000.dat
2015-08-06 19:29:11 UpdateTip: new best=00000bafbc94add76cb75e2ec92894837288a481e5c005f6563d91623bf8bc2c  height=0  log2_work=20.000022  tx=1  date=2014-01-25 16:10:06 progress=0.000001  cache=0
2015-08-06 19:29:12 init message: Verifying blocks...
2015-08-06 19:29:12  block index             482ms
2015-08-06 19:29:12 Wallet disabled!
2015-08-06 19:29:12 init message: Loading masternode cache...
2015-08-06 19:29:12 ERROR: Read : Failed to open file /mnt/data/test-abe-home/.dash/testnet3/mncache.dat
2015-08-06 19:29:12 Missing masternode cache file - mncache.dat, will try to recreate
2015-08-06 19:29:12 init message: Loading budget cache...
2015-08-06 19:29:12 ERROR: Read : Failed to open file /mnt/data/test-abe-home/.dash/testnet3/budget.dat
2015-08-06 19:29:12 Missing budget cache - budget.dat, will try to recreate
2015-08-06 19:29:12 init message: Loading masternode payment cache...
2015-08-06 19:29:12 ERROR: Read : Failed to open file /mnt/data/test-abe-home/.dash/testnet3/mnpayments.dat
2015-08-06 19:29:12 Missing masternode payment cache - mnpayments.dat, will try to recreate

=======================================================
=======================================================

GDB backtrace shows a segfault:

(gdb) file /mnt/data/test-abe-home/bin/dashd
Reading symbols from /mnt/data/test-abe-home/bin/dashd...(no debugging symbols found)...done.
(gdb) run
Starting program: /mnt/data/test-abe-home/bin/dashd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6bc9700 (LWP 22741)]
[New Thread 0x7ffff63c8700 (LWP 22742)]
[New Thread 0x7ffff5bc7700 (LWP 22743)]
[New Thread 0x7ffff53c6700 (LWP 22744)]
[New Thread 0x7ffff4bc5700 (LWP 22745)]
[New Thread 0x7fffeffff700 (LWP 22746)]
[New Thread 0x7fffef7fe700 (LWP 22747)]

Program received signal SIGSEGV, Segmentation fault.
__GI___pthread_mutex_lock (mutex=0x5df) at ../nptl/pthread_mutex_lock.c:66
66      ../nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) backtrace
#0  __GI___pthread_mutex_lock (mutex=0x5df) at ../nptl/pthread_mutex_lock.c:66
#1  0x00005555555dd279 in ?? ()
#2  0x00005555555c7ccc in ?? ()
#3  0x00005555555b305b in ?? ()
#4  0x00005555555bf2df in ?? ()
#5  0x00007ffff6bebec5 in __libc_start_main (main=0x5555555bf2b0, argc=1, argv=0x7fffffffe658, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe648) at libc-start.c:287
#6  0x00005555555b1f69 in ?? ()
#7  0x00007fffffffe648 in ?? ()
#8  0x000000000000001c in ?? ()
#9  0x0000000000000001 in ?? ()
#10 0x00007fffffffe86a in ?? ()
#11 0x0000000000000000 in ?? ()

**Comment by evan82** [comment]
Fixed in https://github.com/dashpay/dash/commit/f94d9803c63d759e63aab06f675fffba8c2b2614 . Thanks for reporting!
