### ISSUE TITLE
dashd crash

### ISSUE THREAD

**Issue by poiuty** [dashpay/dash#756]
https://dl.dropboxusercontent.com/u/59491914/dash/core.tar.gz
```
(gdb) bt
#0  0x00007f3f454c5a15 in std::_Rb_tree_rebalance_for_erase(std::_Rb_tree_node_base*, std::_Rb_tree_node_base&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007f3f45e8f7f9 in ?? ()
#2  0x00007f3f45e4cc73 in ?? ()
#3  0x00007f3f45eda837 in ?? ()
#4  0x00007f3f45ebf074 in ?? ()
#5  0x00007f3f45ed0f5a in ?? ()
#6  0x00007f3f461af0b7 in ?? ()
#7  0x00007f3f44d240a4 in start_thread (arg=0x7f3f0affd700) at pthread_create.c:309
#8  0x00007f3f44a5987d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
bt full
#0  0x00007f3f454c5a15 in std::_Rb_tree_rebalance_for_erase(std::_Rb_tree_node_base*, std::_Rb_tree_node_base&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#1  0x00007f3f45e8f7f9 in ?? ()
No symbol table info available.
#2  0x00007f3f45e4cc73 in ?? ()
No symbol table info available.
#3  0x00007f3f45eda837 in ?? ()
No symbol table info available.
#4  0x00007f3f45ebf074 in ?? ()
No symbol table info available.
#5  0x00007f3f45ed0f5a in ?? ()
No symbol table info available.
#6  0x00007f3f461af0b7 in ?? ()
No symbol table info available.
#7  0x00007f3f44d240a4 in start_thread (arg=0x7f3f0affd700) at pthread_create.c:309
        __res = <optimized out>
        pd = 0x7f3f0affd700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139908744206080, 7330671768809082517, 0, 139909731483744, 139909737853528, 139908744206080, -7222134577457164651, 
                -7222280086362026347}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#8  0x00007f3f44a5987d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
```

**Comment by UdjinM6** [comment]
Do you have few (10-20) last lines of debug.log for this? I think this could be related to 6cfe5bfe2b53d7590ce76c2574f1fb3ace992442

**Comment by poiuty** [comment]
Точно не знаю к какой из ~40 dashd относится этот дамп.
Если напишите, что именно искать в debug.log => могу прогнать через grep

**Comment by poiuty** [comment]
get new crash () => dashd version 120057

```
 bt
#0  0x00007ffae521e067 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffae521f448 in __GI_abort () at abort.c:89
#2  0x00007ffae525c1b4 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0x7ffae5351530 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffae526198e in malloc_printerr (action=1, 
    str=0x7ffae534d646 "free(): invalid pointer", ptr=<optimized out>)
    at malloc.c:4996
#4  0x00007ffae5262696 in _int_free (av=<optimized out>, p=<optimized out>, 
    have_lock=0) at malloc.c:3840
#5  0x00007ffae79d20b9 in deallocate (this=<optimized out>, 
    __p=<optimized out>) at /usr/include/c++/4.9/ext/new_allocator.h:110
#6  deallocate (__a=..., __n=1, __p=<optimized out>)
    at /usr/include/c++/4.9/ext/alloc_traits.h:185
#7  _M_put_node (this=<optimized out>, __p=<optimized out>)
    at /usr/include/c++/4.9/bits/stl_tree.h:389
#8  _M_destroy_node (this=<optimized out>, __p=<optimized out>)
    at /usr/include/c++/4.9/bits/stl_tree.h:410
#9  _M_erase_aux (__position=..., this=0x7ffa980029f8)
    at /usr/include/c++/4.9/bits/stl_tree.h:1867
#10 erase (__position=..., this=0x7ffa980029f8)
    at /usr/include/c++/4.9/bits/stl_tree.h:878
---Type <return> to continue, or q <return> to quit---
#11 _M_erase_aux (__last=..., __first=..., this=0x7ffa980029f8)
    at /usr/include/c++/4.9/bits/stl_tree.h:1881
#12 erase (__last=..., __first=..., this=0x7ffa980029f8)
    at /usr/include/c++/4.9/bits/stl_tree.h:896
#13 std::_Rb_tree<CInv, CInv, std::_Identity<CInv>, std::less<CInv>, std::allocator<CInv> >::erase (this=this@entry=0x7ffa980029f8, __x=...)
    at /usr/include/c++/4.9/bits/stl_tree.h:1892
#14 0x00007ffae79d2323 in erase (__x=..., this=0x7ffa980029f8)
    at /usr/include/c++/4.9/bits/stl_set.h:621
#15 mruset<CInv>::insert (this=this@entry=0x7ffa980029f8, x=...) at mruset.h:49
#16 0x00007ffae79d2485 in CNode::AddInventoryKnown (
    this=this@entry=0x7ffa98002670, inv=...) at net.h:397
#17 0x00007ffae79a644a in ProcessMessage (pfrom=pfrom@entry=0x7ffa98002670, 
    strCommand="inv", vRecv=..., 
    nTimeReceived=nTimeReceived@entry=1460209628277019) at main.cpp:4540
#18 0x00007ffae79ab647 in ProcessMessages (pfrom=0x7ffa98002670)
    at main.cpp:5243
#19 0x00007ffae7a11754 in operator() (a0=<optimized out>, this=<optimized out>)
    at /usr/include/boost/function/function_template.hpp:767
#20 m_invoke (connectionBody=..., this=<optimized out>)
    at /usr/include/boost/signals2/detail/signal_template.hpp:368
#21 operator() (connectionBody=..., this=<optimized out>)
    at /usr/include/boost/signals2/detail/signal_template.hpp:345
---Type <return> to continue, or q <return> to quit---
#22 dereference (this=0x7ffaae978ac0)
    at /usr/include/boost/signals2/detail/slot_call_iterator.hpp:82
#23 dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::signal1_impl<bool, CNode*, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool(CNode*)>, boost::function<bool(const boost::signals2::connection&, CNode*)>, boost::signals2::mutex>::slot_invoker, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot1<bool, CNode*, boost::function<bool(CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot1<bool, CNode*, boost::function<bool(CNode*)> >, boost::signals2::mutex> > > (f=...)
    at /usr/include/boost/iterator/iterator_facade.hpp:514
#24 operator* (this=0x7ffaae978ac0)
    at /usr/include/boost/iterator/iterator_facade.hpp:639
#25 operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::signal1_impl<bool, CNode*, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool(CNode*)>, boost::function<bool(const boost::signals2::connection&, CNode*)>, boost::signals2::mutex>::slot_invoker, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot1<bool, CNode*, boost::function<bool(CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::det---Type <return> to continue, or q <return> to quit---
ail::slot_meta_group, boost::optional<int> >, boost::signals2::slot1<bool, CNode*, boost::function<bool(CNode*)> >, boost::signals2::mutex> > > (last=..., 
    first=..., this=<optimized out>)
    at /usr/include/boost/signals2/optional_last_value.hpp:34
#26 operator()<boost::signals2::optional_last_value<bool>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::signal1_impl<bool, CNode*, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool(CNode*)>, boost::function<bool(const boost::signals2::connection&, CNode*)>, boost::signals2::mutex>::slot_invoker, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot1<bool, CNode*, boost::function<bool(CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot1<bool, CNode*, boost::function<bool(CNode*)> >, boost::signals2::mutex> > > (this=<optimized out>, last=..., first=..., 
    combiner=...)
    at /usr/include/boost/signals2/detail/result_type_wrapper.hpp:53
#27 boost::signals2::detail::signal1_impl<bool, CNode*, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool (CNode*)>, boost::function<bool (boost::signals2::connection const&, CNode*)>, boost::signals2::mutex>::operator()(CNode*) (this=<optimized out>, arg1=arg1@entry=0x7ffa98002670)
    at /usr/include/boost/signals2/detail/signal_template.hpp:246
#28 0x00007ffae79fae52 in operator() (arg1=0x7ffa98002670, 
---Type <return> to continue, or q <return> to quit---
    this=0x7ffae8149b98 <g_signals+24>)
    at /usr/include/boost/signals2/detail/signal_template.hpp:695
#29 ThreadMessageHandler () at net.cpp:1473
#30 0x00007ffae7a08431 in TraceThread<void (*)()> (
    name=0x7ffae7d12a57 "msghand", 
    func=0x7ffae79fabd0 <ThreadMessageHandler()>) at util.h:233
#31 0x00007ffae6e31aea in ?? ()
   from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0
#32 0x00007ffae559c0a4 in start_thread (arg=0x7ffaae979700)
    at pthread_create.c:309
#33 0x00007ffae52d187d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by poiuty** [comment]
new crash (dashd version 120057)
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `dashd -datadir=/home/dash/data/92.222.206.197 -daemon'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  operator< (a=..., b=...) at protocol.cpp:139
139	    return (a.type < b.type || (a.type == b.type && a.hash < b.hash));
(gdb) bt
#0  operator< (a=..., b=...) at protocol.cpp:139
#1  0x00007efc0731318b in operator() (this=0x7efbb8005908, __y=..., __x=...)
    at /usr/include/c++/4.9/bits/stl_function.h:371
#2  _M_get_insert_unique_pos (__k=..., this=0x7efbb8005908)
    at /usr/include/c++/4.9/bits/stl_tree.h:1445
#3  _M_insert_unique (__v=..., this=0x7efbb8005908)
    at /usr/include/c++/4.9/bits/stl_tree.h:1498
#4  insert (__x=..., this=0x7efbb8005908)
    at /usr/include/c++/4.9/bits/stl_set.h:502
#5  mruset<CInv>::insert (this=this@entry=0x7efbb8005908, x=...) at mruset.h:46
#6  0x00007efc07313485 in CNode::AddInventoryKnown (
    this=this@entry=0x7efbb8005580, inv=...) at net.h:397
#7  0x00007efc072e744a in ProcessMessage (pfrom=pfrom@entry=0x7efbb8005580, 
    strCommand="inv", vRecv=..., 
    nTimeReceived=nTimeReceived@entry=1460710270193270) at main.cpp:4540
#8  0x00007efc072ec647 in ProcessMessages (pfrom=0x7efbb8005580)
    at main.cpp:5243
#9  0x00007efc07352754 in operator() (a0=<optimized out>, this=<optimized out>)
    at /usr/include/boost/function/function_template.hpp:767
#10 m_invoke (connectionBody=..., this=<optimized out>)
    at /usr/include/boost/signals2/detail/signal_template.hpp:368
#11 operator() (connectionBody=..., this=<optimized out>)
    at /usr/include/boost/signals2/detail/signal_template.hpp:345
---Type <return> to continue, or q <return> to quit---
#12 dereference (this=0x7efbcdcb8ac0)
    at /usr/include/boost/signals2/detail/slot_call_iterator.hpp:82
#13 dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::signal1_impl<bool, CNode*, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool(CNode*)>, boost::function<bool(const boost::signals2::connection&, CNode*)>, boost::signals2::mutex>::slot_invoker, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot1<bool, CNode*, boost::function<bool(CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot1<bool, CNode*, boost::function<bool(CNode*)> >, boost::signals2::mutex> > > (f=...)
    at /usr/include/boost/iterator/iterator_facade.hpp:514
#14 operator* (this=0x7efbcdcb8ac0)
    at /usr/include/boost/iterator/iterator_facade.hpp:639
#15 operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::signal1_impl<bool, CNode*, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool(CNode*)>, boost::function<bool(const boost::signals2::connection&, CNode*)>, boost::signals2::mutex>::slot_invoker, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot1<bool, CNode*, boost::function<bool(CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::det---Type <return> to continue, or q <return> to quit---
ail::slot_meta_group, boost::optional<int> >, boost::signals2::slot1<bool, CNode*, boost::function<bool(CNode*)> >, boost::signals2::mutex> > > (last=..., 
    first=..., this=<optimized out>)
    at /usr/include/boost/signals2/optional_last_value.hpp:34
#16 operator()<boost::signals2::optional_last_value<bool>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::signal1_impl<bool, CNode*, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool(CNode*)>, boost::function<bool(const boost::signals2::connection&, CNode*)>, boost::signals2::mutex>::slot_invoker, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot1<bool, CNode*, boost::function<bool(CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot1<bool, CNode*, boost::function<bool(CNode*)> >, boost::signals2::mutex> > > (this=<optimized out>, last=..., first=..., 
    combiner=...)
    at /usr/include/boost/signals2/detail/result_type_wrapper.hpp:53
#17 boost::signals2::detail::signal1_impl<bool, CNode*, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool (CNode*)>, boost::function<bool (boost::signals2::connection const&, CNode*)>, boost::signals2::mutex>::operator()(CNode*) (this=<optimized out>, arg1=arg1@entry=0x7efbb8005580)
    at /usr/include/boost/signals2/detail/signal_template.hpp:246
#18 0x00007efc0733be52 in operator() (arg1=0x7efbb8005580, 
---Type <return> to continue, or q <return> to quit---
    this=0x7efc07a8ab98 <g_signals+24>)
    at /usr/include/boost/signals2/detail/signal_template.hpp:695
#19 ThreadMessageHandler () at net.cpp:1473
#20 0x00007efc07349431 in TraceThread<void (*)()> (
    name=0x7efc07653a57 "msghand", 
    func=0x7efc0733bbd0 <ThreadMessageHandler()>) at util.h:233
#21 0x00007efc06772aea in ?? ()
   from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0
#22 0x00007efc04edd0a4 in start_thread (arg=0x7efbcdcb9700)
    at pthread_create.c:309
#23 0x00007efc04c1287d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by poiuty** [comment]
```
(gdb) bt
#0  0x00007fe61f5c4067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fe61f5c5448 in __GI_abort () at abort.c:89
#2  0x00007fe61f6021b4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fe61f6f7530 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007fe61f60798e in malloc_printerr (action=1, str=0x7fe61f6f7718 "double free or corruption (fasttop)", ptr=<optimized out>) at malloc.c:4996
#4  0x00007fe61f608696 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007fe621d780b9 in deallocate (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.9/ext/new_allocator.h:110
#6  deallocate (__a=..., __n=1, __p=<optimized out>) at /usr/include/c++/4.9/ext/alloc_traits.h:185
#7  _M_put_node (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.9/bits/stl_tree.h:389
#8  _M_destroy_node (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.9/bits/stl_tree.h:410
#9  _M_erase_aux (__position=..., this=0x7fe5e002d918) at /usr/include/c++/4.9/bits/stl_tree.h:1867
#10 erase (__position=..., this=0x7fe5e002d918) at /usr/include/c++/4.9/bits/stl_tree.h:878
#11 _M_erase_aux (__last=..., __first=..., this=0x7fe5e002d918) at /usr/include/c++/4.9/bits/stl_tree.h:1881
#12 erase (__last=..., __first=..., this=0x7fe5e002d918) at /usr/include/c++/4.9/bits/stl_tree.h:896
#13 std::_Rb_tree<CInv, CInv, std::_Identity<CInv>, std::less<CInv>, std::allocator<CInv> >::erase (this=this@entry=0x7fe5e002d918, __x=...)
    at /usr/include/c++/4.9/bits/stl_tree.h:1892
#14 0x00007fe621d78323 in erase (__x=..., this=0x7fe5e002d918) at /usr/include/c++/4.9/bits/stl_set.h:621
#15 mruset<CInv>::insert (this=this@entry=0x7fe5e002d918, x=...) at mruset.h:49
#16 0x00007fe621d3b9a0 in SendMessages (pto=0x7fe5e002d590, fSendTrickle=false) at main.cpp:5447
#17 0x00007fe621db7f42 in operator() (a1=<optimized out>, a0=<optimized out>, this=<optimized out>)
    at /usr/include/boost/function/function_template.hpp:767
#18 m_invoke (connectionBody=..., this=<optimized out>) at /usr/include/boost/signals2/detail/signal_template.hpp:368
#19 operator() (connectionBody=..., this=<optimized out>) at /usr/include/boost/signals2/detail/signal_template.hpp:345
#20 dereference (this=0x7fe5e7cc7ac0) at /usr/include/boost/signals2/detail/slot_call_iterator.hpp:82
#21 dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::signal2_impl<bool, CNode*, bool, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool(CNode*, bool)>, boost::function<bool(const boost::signals2::connection&, CNode*, bool)>, boost::signals2::mutex>::slot_invoker, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot2<bool, CNode*, bool, boost::function<bool(CNode*, bool)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot2<bool, CNode*, bool, boost---Type <return> to continue, or q <return> to quit---
::function<bool(CNode*, bool)> >, boost::signals2::mutex> > > (f=...) at /usr/include/boost/iterator/iterator_facade.hpp:514
#22 operator* (this=0x7fe5e7cc7ac0) at /usr/include/boost/iterator/iterator_facade.hpp:639
#23 operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::signal2_impl<bool, CNode*, bool, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool(CNode*, bool)>, boost::function<bool(const boost::signals2::connection&, CNode*, bool)>, boost::signals2::mutex>::slot_invoker, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot2<bool, CNode*, bool, boost::function<bool(CNode*, bool)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot2<bool, CNode*, bool, boost::function<bool(CNode*, bool)> >, boost::signals2::mutex> > > (last=..., first=..., this=<optimized out>)
    at /usr/include/boost/signals2/optional_last_value.hpp:34
#24 operator()<boost::signals2::optional_last_value<bool>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::signal2_impl<bool, CNode*, bool, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool(CNode*, bool)>, boost::function<bool(const boost::signals2::connection&, CNode*, bool)>, boost::signals2::mutex>::slot_invoker, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot2<bool, CNode*, bool, boost::function<bool(CNode*, bool)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot2<bool, CNode*, bool, boost::function<bool(CNode*, bool)> >, boost::signals2::mutex> > > (this=<optimized out>, last=..., first=..., 
    combiner=...) at /usr/include/boost/signals2/detail/result_type_wrapper.hpp:53
#25 boost::signals2::detail::signal2_impl<bool, CNode*, bool, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool (CNode*, bool)>, boost::function<bool (boost::signals2::connection const&, CNode*, bool)>, boost::signals2::mutex>::operator()(CNode*, bool) (
    this=<optimized out>, arg1=arg1@entry=0x7fe5e002d590, arg2=false) at /usr/include/boost/signals2/detail/signal_template.hpp:246
#26 0x00007fe621da0db3 in operator() (arg2=<optimized out>, arg1=0x7fe5e002d590, this=0x7fe6224efbb0 <g_signals+48>)
    at /usr/include/boost/signals2/detail/signal_template.hpp:695
#27 ThreadMessageHandler () at net.cpp:1491
#28 0x00007fe621dae431 in TraceThread<void (*)()> (name=0x7fe6220b8a57 "msghand", func=0x7fe621da0bd0 <ThreadMessageHandler()>) at util.h:233
#29 0x00007fe6211d7aea in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0
#30 0x00007fe61f9420a4 in start_thread (arg=0x7fe5e7cc8700) at pthread_create.c:309
#31 0x00007fe61f67787d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by poiuty** [comment]
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `dashd -datadir=/home/dash/data/5.196.111.23 -daemon'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f0b3af0d067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt 
#0  0x00007f0b3af0d067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f0b3af0e448 in __GI_abort () at abort.c:89
#2  0x00007f0b3af4b1b4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7f0b3b040530 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007f0b3af5098e in malloc_printerr (action=1, str=0x7f0b3b040718 "double free or corruption (fasttop)", ptr=<optimized out>) at malloc.c:4996
#4  0x00007f0b3af51696 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007f0b3d8db836 in deallocate (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.9/ext/new_allocator.h:110
#6  deallocate (__a=..., __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.9/ext/alloc_traits.h:185
#7  _M_deallocate (this=<optimized out>, __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.9/bits/stl_vector.h:178
#8  ~_Vector_base (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/4.9/bits/stl_vector.h:160
#9  ~vector (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/4.9/bits/stl_vector.h:425
#10 CDarksendQueue::~CDarksendQueue (this=0x7f0aeb93d590, __in_chrg=<optimized out>) at darksend.h:158
#11 0x00007f0b3d8daf74 in destroy (this=0x7f0b3de3b810 <vecDarksendQueue>, __p=<optimized out>) at /usr/include/c++/4.9/ext/new_allocator.h:133
#12 destroy (__a=..., __p=<optimized out>) at /usr/include/c++/4.9/ext/alloc_traits.h:192
#13 _M_erase (__position=..., this=0x7f0b3de3b810 <vecDarksendQueue>) at /usr/include/c++/4.9/bits/vector.tcc:147
#14 erase (__position=..., this=0x7f0b3de3b810 <vecDarksendQueue>) at /usr/include/c++/4.9/bits/stl_vector.h:1150
#15 CDarksendPool::CheckTimeout (this=this@entry=0x7f0b3de3b840 <darkSendPool>) at darksend.cpp:821
#16 0x00007f0b3d8db553 in ThreadCheckDarkSendPool () at darksend.cpp:2259
#17 0x00007f0b3cb20aea in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0
#18 0x00007f0b3b28b0a4 in start_thread (arg=0x7f0b11355700) at pthread_create.c:309
#19 0x00007f0b3afc087d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
